import { Router } from 'express';
import { authMiddleware } from '../../common/infrastructure/middleware/auth.middleware';
import { agencyMiddleware } from '../../common/infrastructure/middleware/agency.middleware';
import { accountRoutes } from '../../modules/account-management';
import { agencyRoutes } from '../../modules/agency';
import { activityAuditRoutes } from '../../modules/activity-audit';
import { assistantRoutes } from '../../modules/assistant';
import { automationRoutes } from '../../modules/automation';
import { calendarRoutes } from '../../modules/calendar';
import { communicationRoutes } from '../../modules/communication';
import { currencyRoutes } from '../../modules/currency';
import { customerSuccessRoutes } from '../../modules/customer-success';
import { fileStorageRoutes } from '../../modules/file-storage';
import { iamRoutes, userManagementRoutes } from '../../modules/iam';
import { knowledgeBaseRoutes } from '../../modules/knowledge-base';
import { leadRoutes } from '../../modules/lead-management';
import { matchingRoutes, publicSelectionsRoutes, selectionsRoutes } from '../../modules/matching';
import { notificationRoutes } from '../../modules/notification-center';
import { propertyRoutes } from '../../modules/property-catalog';
import { referenceDataRoutes } from '../../modules/reference-data';
import { reportingRoutes } from '../../modules/reporting';
import { salesRoutes } from '../../modules/sales-pipeline';
import { showingRoutes } from '../../modules/showings';
import { systemRoutes } from '../../modules/system';
import { taskRoutes } from '../../modules/task-management';
import { templateRoutes } from '../../modules/template-management';

const apiRouter = Router();

apiRouter.get('/health', (_req, res) => res.status(200).json({ status: 'ok' }));
apiRouter.use('/auth', iamRoutes);
apiRouter.use(publicSelectionsRoutes);
apiRouter.use(authMiddleware);
apiRouter.use(agencyMiddleware);
apiRouter.use(agencyRoutes);
apiRouter.use(accountRoutes);
apiRouter.use(userManagementRoutes);
apiRouter.use(referenceDataRoutes);
apiRouter.use(fileStorageRoutes);
apiRouter.use(currencyRoutes);
apiRouter.use(propertyRoutes);
apiRouter.use(taskRoutes);
apiRouter.use(activityAuditRoutes);
apiRouter.use(templateRoutes);
apiRouter.use(knowledgeBaseRoutes);
apiRouter.use(customerSuccessRoutes);
apiRouter.use(automationRoutes);
apiRouter.use(calendarRoutes);
apiRouter.use(communicationRoutes);
apiRouter.use(leadRoutes);
apiRouter.use(matchingRoutes);
apiRouter.use(selectionsRoutes);
apiRouter.use(salesRoutes);
apiRouter.use(showingRoutes);
apiRouter.use(reportingRoutes);
apiRouter.use(notificationRoutes);
apiRouter.use(assistantRoutes);
apiRouter.use(systemRoutes);

export const routes = apiRouter;
